### ISSUE TITLE
Parent categories should ONLY have latest products

### ISSUE THREAD

**Issue by ortokore** [Clan-Creativo/openbox#1]
Parent categories like Longboards, Skateboards and Patines should only display 12 latest products instead of having different rows for product sections. The only parent category that will remain with that layout will be Otros that will have a row for each product type (shoes, clothing, surf, etc)

**Comment by mediamilan** [comment]
Fixed up.
Now showing 15 recent products.

**Comment by ortokore** [comment]
Remember that the latest products should be categorized. For longboards I only need to see the latest Longboard products, and so forth.

**Comment by mediamilan** [comment]
Unfortunately WooCommerce does not give its shortcode that functionality.

Have to find a way around it.

On Fri, Jun 12, 2015 at 7:27 PM, Oscar Cartagena notifications@github.com
wrote:

> Remember that the latest products should be categorized. For longboards I
> only need to see the latest Longboard products, and so forth.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Clan-Creativo/openbox/issues/1#issuecomment-111501139
> .

## 

Cheers!
Rajendra Prasadh JC
Ph: +91 950 3303 440

**Comment by ortokore** [comment]
Fuckity fuck fuck. It would seem that Woocommerce does not want us to finish this.. ever.

**Comment by ortokore** [comment]
Any way around this? this is CRUCIAL - the site doesn't work if we can't display latest products on a per parent category basis

**Comment by mediamilan** [comment]
http://gs-openboxstore.cl.s207584.gridserver.com/product-category/longboard/
Finished the functionality using 'Destacado' as discussed last night.

**Comment by ortokore** [comment]
Is it applied to all parent cats?

**Comment by mediamilan** [comment]
Yes.

On Wed, Jun 17, 2015 at 5:54 PM, Oscar Cartagena notifications@github.com
wrote:

> Is it applied to all parent cats?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Clan-Creativo/openbox/issues/1#issuecomment-112780171
> .

## 

Cheers!
Rajendra Prasadh JC
Ph: +91 950 3303 440
