### ISSUE TITLE
Footer Social Media links

### ISSUE THREAD

**Issue by ortokore** [Clan-Creativo/openbox#10]
These links don't have the url's

![screenshot 2015-06-10 10 14 32](https://cloud.githubusercontent.com/assets/3596525/8083229/6c009f18-0f59-11e5-976c-66e87b3007f4.png)

**Comment by leninlee** [comment]
Fixed

**Comment by leninlee** [comment]
https://instagram.com/openboxstore
https://www.facebook.com/openbox.store
https://twitter.com/openboxstore
https://instagram.com/openboxstore
