### ISSUE TITLE
Newsletter connection

### ISSUE THREAD

**Issue by ortokore** [Clan-Creativo/openbox#11]
The newsletter input field at the footer and header should be connected to a Mailchimp account that the client will be creating today. Also those social media links do not have the URL's

![screenshot 2015-06-10 10 19 01](https://cloud.githubusercontent.com/assets/3596525/8083323/191d33e6-0f5a-11e5-84d2-be2b68b17146.png)

![screenshot 2015-06-10 10 15 14](https://cloud.githubusercontent.com/assets/3596525/8083261/ae8afcc0-0f59-11e5-90ae-d644a431b33f.png)

**Comment by leninlee** [comment]
Social media links working now.
