### ISSUE TITLE
What happens to the breadcrumbs when I do a brand search or filter search?

### ISSUE THREAD

**Issue by ortokore** [Clan-Creativo/openbox#13]
It just displays HOME.... shouldn't it reflect a bit more info? is this feasible?

**Comment by mediamilan** [comment]
@leninlee
See this link.
http://gs-openboxstore.cl.s207584.gridserver.com/marcas/aera/

**Comment by alvarocova** [comment]
Is it possible that the breadcrums are somthing like HOME  / LONGBOARD / TABLAS PARA ARMAR without the SHOP part, beacuse when you click it takes you to someplace else ![screen shot 2015-06-23 at 1 53 28 pm](https://cloud.githubusercontent.com/assets/13010249/8311835/6c5d4f50-19af-11e5-8c1e-49393fa4c5fd.png)
