### ISSUE TITLE
Image quality for the product listings?

### ISSUE THREAD

**Issue by ortokore** [Clan-Creativo/openbox#14]
For some reason the images in the product listings are showing up a bit blurry, even though the original images are quite big. Can we make these images look sharper?

![screenshot 2015-06-10 10 21 42](https://cloud.githubusercontent.com/assets/3596525/8083385/8e7e6b32-0f5a-11e5-9806-635dae4077ac.png)
![screenshot 2015-06-10 10 21 26](https://cloud.githubusercontent.com/assets/3596525/8083386/8e9fe6d6-0f5a-11e5-8a14-2e1bea83dd10.png)

**Comment by mediamilan** [comment]
Fixed.

**Comment by ortokore** [comment]
they still look blurry... how come? some products don't though.
![screenshot 2015-06-15 12 46 20](https://cloud.githubusercontent.com/assets/3596525/8163964/89cb1828-135c-11e5-99d5-f7e429912bb2.png)

**Comment by mediamilan** [comment]
Fixed this by increasing the resolution.
Check and let me know if its fine.

**Comment by ortokore** [comment]
I think it looks good. I'm waiting for client confirmation.
