### ISSUE TITLE
Search field in Nav

### ISSUE THREAD

**Issue by ortokore** [Clan-Creativo/openbox#15]
First, please center the looking glass in the button 
![screenshot 2015-06-10 10 23 43](https://cloud.githubusercontent.com/assets/3596525/8083422/c6bc3aa6-0f5a-11e5-84ff-0e810e527bfc.png)

Second, let's remove the focus blurring in the input field AND set that font to normal or light weight, looks broken and shitty as it is now.
![screenshot 2015-06-10 10 23 33](https://cloud.githubusercontent.com/assets/3596525/8083431/df7dc2f8-0f5a-11e5-8ab8-31026e1cc579.png)

**Comment by leninlee** [comment]
Fixed
