### ISSUE TITLE
Soft shadows on elements

### ISSUE THREAD

**Issue by ortokore** [Clan-Creativo/openbox#16]
Please let's remove ALL drop shadows on all items in the page, for example
![screenshot 2015-06-10 10 29 18](https://cloud.githubusercontent.com/assets/3596525/8083527/a503b668-0f5b-11e5-8fa5-cb674f578ee1.png)

remove the dropshadow from the revslider AND also from the radio buttons

And on the product, the FLEX increment has no glow/drop shadow when focused, but the quantity does
![screenshot 2015-06-10 10 29 45](https://cloud.githubusercontent.com/assets/3596525/8083535/b4dc2bce-0f5b-11e5-8bbb-4f1e75e7b87d.png)

**Comment by leninlee** [comment]
Fixed
