### ISSUE TITLE
Shipping Matrix and Shipping costs

### ISSUE THREAD

**Issue by ortokore** [Clan-Creativo/openbox#22]
What do we do about the shipping matrix? how are we going to go about this? any ideas? we NEED to sort this out ASAP - if we don't have this working properly we cannot begin the Transbank certification, hence we can't deploy the site, so we need this working now!

**Comment by mediamilan** [comment]
While I am fixing the bugs Openbox you can show some proper plugin Oscar. 
So it will be helpful.
