### ISSUE TITLE
Instagram feed on homepage

### ISSUE THREAD

**Issue by ortokore** [Clan-Creativo/openbox#23]
We need the correct instagram feed for the homepage. The instagram account is: https://instagram.com/openboxstore

please let me know if you need anything more for this to work.

**Comment by leninlee** [comment]
Fixed

http://gs-openboxstore.cl.s207584.gridserver.com/wp-admin/widgets.php
![Uploading Screenshot_061515_122217_PM.jpg…]()
![Uploading Screenshot_061515_122142_PM.jpg…]()
