### ISSUE TITLE
Order confirmation Email

### ISSUE THREAD

**Issue by ortokore** [Clan-Creativo/openbox#27]
How can we edit this so all the message is in spanish, including the email title?

![screenshot 2015-06-10 11 06 15](https://cloud.githubusercontent.com/assets/3596525/8084288/b52bc792-0f60-11e5-8fbe-af2428a3eccb.png)

**Comment by leninlee** [comment]
Fixed

![screenshot_061915_124520_pm](https://cloud.githubusercontent.com/assets/5433592/8248852/593caa1e-1681-11e5-9a9b-99154c5d326d.jpg)
![Uploading Screenshot_061915_124717_PM.jpg…]()

**Comment by leninlee** [comment]
![screenshot_061915_124839_pm](https://cloud.githubusercontent.com/assets/5433592/8248868/9315d3fa-1681-11e5-889c-d25e19bf32e8.jpg)
