### ISSUE TITLE
Checkout Process

### ISSUE THREAD

**Issue by ortokore** [Clan-Creativo/openbox#28]
I placed and order, finished the whole process but the STEPS in the checkout got stuck at 2.

![screenshot 2015-06-10 11 07 26](https://cloud.githubusercontent.com/assets/3596525/8084328/daea32ac-0f60-11e5-8a78-a05a29e4a20b.png)

**Comment by ortokore** [comment]
is this done?

**Comment by mediamilan** [comment]
yes this is done. I recieve the emails of all ur orders.

**Comment by ortokore** [comment]
I know, but I still see it stuck at STEP 2. 

First step should be: Product info, client info, shipping address

Step two: A message box so they can send any special notes, shipping cost, terms and conditions for the sale

Step three: Checkout confirmation.... product listing with total price (taxes and shipping included), shipping and billing address, type of payment (bank transfer, local pickup, webpay/transbank) 

STEP 4: GO TO WEBPAY AND PAY UP, AFTER YOU'VE PAYED YOU SHOULD GO TO ONE OF TWO PAGES: SUCCESS PAGE AND ERROR PAGE.

**Comment by mediamilan** [comment]
But this is not how Woo works. It has its own process. Please advice how it
should be done.

On Tue, Jun 16, 2015 at 9:52 PM, Oscar Cartagena notifications@github.com
wrote:

> I know, but I still see it stuck at STEP 2.
> 
> First step should be: Product info, client info, shipping address
> 
> Step two: A message box so they can send any special notes, shipping cost,
> terms and conditions for the sale
> 
> Step three: Checkout confirmation.... product listing with total price
> (taxes and shipping included), shipping and billing address, type of
> payment (bank transfer, local pickup, webpay/transbank)
> 
> STEP 4: GO TO WEBPAY AND PAY UP, AFTER YOU'VE PAYED YOU SHOULD GO TO ONE
> OF TWO PAGES: SUCCESS PAGE AND ERROR PAGE.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Clan-Creativo/openbox/issues/28#issuecomment-112486503
> .

## 

Cheers!
Rajendra Prasadh JC
Ph: +91 950 3303 440

**Comment by ortokore** [comment]
We'll stick to two steps. Remove the 3rd step from that header.

step 1: DATOS DEL CLIENTE Y DIRECCIÓN DE ENVÍO
step 2: CONFIRMACIÓN DEL PEDIDO

**Comment by leninlee** [comment]
Fixed
![screenshot_061915_121936_pm](https://cloud.githubusercontent.com/assets/5433592/8248516/96fd6054-167d-11e5-9c2d-b27e716fcf41.jpg)
