### ISSUE TITLE
Create Categories for filtering through Styles

### ISSUE THREAD

**Issue by ortokore** [Clan-Creativo/openbox#29]
In the attached screenshot you can see the Category names for each Parent Category. 'Otros' does not have style filtering.

Now, I didn't create the categories myself because each parent category (Longboards, Skateboards, Rollerskates/Patines) has a different filtering set, or styles.... so I didn't know if these categories shoud be children of the parent category or just categories. You decide.

![screenshot 2015-06-10 18 01 15](https://cloud.githubusercontent.com/assets/3596525/8094000/af910fec-0f9a-11e5-9fa7-148fc409c877.png)

**Comment by mediamilan** [comment]
THis is same as Issue #5

**Comment by mediamilan** [comment]
Please close this issue as I am fixing it in #5.

**Comment by mediamilan** [comment]
Created these list of Estilos. So now you can close them.
