### ISSUE TITLE
When parent category LONGBOARDS is clicked, the sidebar info is wrong

### ISSUE THREAD

**Issue by ortokore** [Clan-Creativo/openbox#3]
This is wrong
![screenshot 2015-06-10 10 01 56](https://cloud.githubusercontent.com/assets/3596525/8082964/ade29c6c-0f57-11e5-8d24-86f06a0face1.png)

This is the one that should be showing up -- also, let's make the space for the menu higher so the sidebar nav fits without scrolling
![screenshot 2015-06-10 10 02 06](https://cloud.githubusercontent.com/assets/3596525/8082971/bba3bdea-0f57-11e5-9962-accd59af21fa.png)

**Comment by mediamilan** [comment]
![products_ _open_box_store_ _wordpress](https://cloud.githubusercontent.com/assets/2662306/8128959/b64a299e-1121-11e5-8c78-582f5d8f67ca.png)

**Comment by mediamilan** [comment]
![open_box_store___product_categories___longboard](https://cloud.githubusercontent.com/assets/2662306/8128967/c5ac3ac6-1121-11e5-9cd7-976edec78664.png)
