### ISSUE TITLE
Rollerskates page is screwed up

### ISSUE THREAD

**Issue by ortokore** [Clan-Creativo/openbox#31]
Ok two things here, one is that the page is obvioulsy screwed up.

Second is that on top it says 'SOLO TABLA' which means 'BOARD ONLY' so that's not supposed to be there for rollerskates.

![screenshot 2015-06-12 10 58 49](https://cloud.githubusercontent.com/assets/3596525/8131652/1b820974-10f2-11e5-8d01-18c6faf9456e.png)

**Comment by leninlee** [comment]
Fixed.
