### ISSUE TITLE
Style Filtering should be categorized

### ISSUE THREAD

**Issue by ortokore** [Clan-Creativo/openbox#32]
For the Style Filtering in the sidebar, it should be on a per category basis. For longboards there should only be 7 items on that list, and so forth based on the image with the style categories I posted in the main issue.

![screenshot 2015-06-12 11 01 42](https://cloud.githubusercontent.com/assets/3596525/8131704/8279dbb6-10f2-11e5-95c0-05ac697dc1b9.png)

**Comment by mediamilan** [comment]
Like Marcas Estilo is not linked to any parent category (longboard, skate, ...).
So we cannot define a relationship between these and filter it.
This cannot be done.

**Comment by ortokore** [comment]
So are we going to hardcode these filters onto each sidebar for each parent category?

**Comment by mediamilan** [comment]
Fixed!
