### ISSUE TITLE
Missing QUIENES SOMOS text before the team listing

### ISSUE THREAD

**Issue by ortokore** [Clan-Creativo/openbox#33]
this is now:
![screenshot 2015-06-12 11 09 27](https://cloud.githubusercontent.com/assets/3596525/8131847/896351d6-10f3-11e5-9fad-8af065cf3043.png)

this is how it should be:
![screenshot 2015-06-12 11 11 44](https://cloud.githubusercontent.com/assets/3596525/8131876/ba743b46-10f3-11e5-9e82-f2f58b0e2319.png)

**Comment by leninlee** [comment]
Fixed

![screenshot_061515_043828_pm](https://cloud.githubusercontent.com/assets/5433592/8158694/05172894-137d-11e5-957c-1279ec84bd23.jpg)
