### ISSUE TITLE
Product image proportion

### ISSUE THREAD

**Issue by ortokore** [Clan-Creativo/openbox#35]
Seems like there's a width/height issue with the product images, as the wheels look oval instead of round. There also seems to be some sort of issue with the image quality and color? weird.

**Comment by mediamilan** [comment]
Checked few random pages and they were fine. Can you please attach some screenshot?

**Comment by ortokore** [comment]
these are the images the client sent to show the issue
![screen shot 2015-06-13 at 2 05 06 pm](https://cloud.githubusercontent.com/assets/3596525/8164028/f1e41db0-135c-11e5-81e3-63bca1b8700a.png)
![screen shot 2015-06-13 at 2 02 50 pm](https://cloud.githubusercontent.com/assets/3596525/8164029/f474f112-135c-11e5-9783-098cd1c1facd.png)

**Comment by mediamilan** [comment]
![open_box_store___product_categories___ruedas](https://cloud.githubusercontent.com/assets/2662306/8179027/4778c2c4-1431-11e5-8c63-0582ff38f053.png)

**Comment by mediamilan** [comment]
![untitled-1___100___rgb_8____](https://cloud.githubusercontent.com/assets/2662306/8179037/59644c2e-1431-11e5-9a47-9054db59775a.png)

**Comment by ortokore** [comment]
I found out what the issue with the proportion is.... each product image has a min-height of 220px and it seems like not all pictures are the same size, so some are stretching and some aren't. If you look at the wheels under longboards, inspect element and turn off that min-height class in the css inspector you'll see the proportion issue clearly. I think that the first thing to do should be to check if the images of the wheels that are stretching out are different than the others. If this is the case I'll ask the client to upload images under a standard format, but this needs to be checked out first thoroughly.
