### ISSUE TITLE
Zoom is screwing up

### ISSUE THREAD

**Issue by ortokore** [Clan-Creativo/openbox#38]
![screenshot 2015-06-15 13 19 42](https://cloud.githubusercontent.com/assets/3596525/8164747/887a6532-1361-11e5-84f7-f2cf1746eaa9.png)

**Comment by ortokore** [comment]
Also, zoom should actually ZOOM.

**Comment by mediamilan** [comment]
For the image to actually zoom the uploaded image should be big.
For ghost type of glitch its fixed.
