### ISSUE TITLE
Flex and product attribute

### ISSUE THREAD

**Issue by ortokore** [Clan-Creativo/openbox#41]
Ok guys, had a talk with the client and we came to the conclusion of technically forgetting about the Flex attribute as we've been trying to handle up to now.

Now the Flex attribute will ONLY BE SHOWN IF it's the selected attribute to base the product's variability.

The dropdown that's on the side of the quantity will be RESERVED for the sole purpose of displaying the info of the attribute that's selected as the main ID For the product variables.

This works the same on all products.

**Comment by leninlee** [comment]
Fixed
http://gs-openboxstore.cl.s207584.gridserver.com/shop/longboard/bustin-maestro-38-completa/

![screenshot_061615_074625_pm](https://cloud.githubusercontent.com/assets/5433592/8186727/959f4bb6-1469-11e5-8bf5-64c1e6879804.jpg)
![Uploading Screenshot_061615_085151_PM.jpg…]()
