### ISSUE TITLE
Login / Registration

### ISSUE THREAD

**Issue by ortokore** [Clan-Creativo/openbox#43]
There is a text beneath the login info that should only show up after you've registered successfully.

![screenshot 2015-06-15 18 04 58](https://cloud.githubusercontent.com/assets/3596525/8170715/28238380-1389-11e5-8847-274e22689fb7.png)

this is the text in question

![screenshot 2015-06-15 18 05 03](https://cloud.githubusercontent.com/assets/3596525/8170730/3a66df10-1389-11e5-8dbc-ed90be6f7364.png)

Also, why isn't there a button to  help me if I've forgotten my password? in the box on the homepage we're also lacking that.

![screenshot 2015-06-15 18 07 40](https://cloud.githubusercontent.com/assets/3596525/8170766/6d7f648a-1389-11e5-9c99-6bfd8774402e.png)

**Comment by ortokore** [comment]
Also that email that says cualquiercorreo@noimpotanada.com should be THE USER'S EMAIL -- that text says: "A message with instructions to change your password has been sent to the email: x@xxx.com"

I think there are some things in this whole process that are wrong, I think I'm going to need to know where I can change these texts so I can go over 'em with the client at some point.

**Comment by mediamilan** [comment]
Fixed the Registration process and Created a forgot password page.
1. Registration - http://gs-openboxstore.cl.s207584.gridserver.com/registration/ (page_registration.php)
2. Forgot Password - http://gs-openboxstore.cl.s207584.gridserver.com/forgot-password/ (page_forgotPassword.php)
3. Login in Header - (header.php)

You can change the texts in these files.
