### ISSUE TITLE
Buy Now and Quantity selector is misaligned

### ISSUE THREAD

**Issue by ortokore** [Clan-Creativo/openbox#44]
![screenshot 2015-06-16 13 13 54](https://cloud.githubusercontent.com/assets/3596525/8188008/93d37b80-1429-11e5-8c5b-fb9fe019d092.png)

**Comment by leninlee** [comment]
Fixed

![screenshot_061915_115740_am](https://cloud.githubusercontent.com/assets/5433592/8248265/6c6e6106-167a-11e5-892c-7e59f8d1bfbd.jpg)
