### ISSUE TITLE
Style Filtering is wrong when clicked on

### ISSUE THREAD

**Issue by ortokore** [Clan-Creativo/openbox#45]
I clicked on the 'Street' style filtering on the Longboards sidebar and after the new page loaded, the filtering showed all styles.
![screenshot 2015-06-16 13 15 27](https://cloud.githubusercontent.com/assets/3596525/8188068/d9f32930-1429-11e5-903c-0449c2c907db.png)

**Comment by mediamilan** [comment]
http://gs-openboxstore.cl.s207584.gridserver.com/estilo/carve/
Fixed.

**Comment by ortokore** [comment]
Roger that. Did anyone ever check the breadcrumbs? would be nice to have the breadcrumbs display what you're looking at.

**Comment by mediamilan** [comment]
Using woocommerce breadcrumbs only. You anyway have issue #13 listed.
So close this bug please.
