### ISSUE TITLE
Check this on Zoom

### ISSUE THREAD

**Issue by ortokore** [Clan-Creativo/openbox#46]
http://gs-openboxstore.cl.s207584.gridserver.com/shop/longboard/bustin-ratarang-2014-deck/

Look at the zoomed image, it's cropped.

**Comment by leninlee** [comment]
FIXED

![screenshot_061915_114613_am](https://cloud.githubusercontent.com/assets/5433592/8248118/dc162df6-1678-11e5-90c8-badfeba3acbb.jpg)
