### ISSUE TITLE
Pagination item

### ISSUE THREAD

**Issue by ortokore** [Clan-Creativo/openbox#47]
For the pagination the style is inversed, the current page and all rollover/active/etc actions are gold, the rest is black.

![screen shot 2015-06-16 at 2 05 07 pm](https://cloud.githubusercontent.com/assets/3596525/8212758/e98f1dfc-14f3-11e5-8e64-8c5b9536309a.png)

**Comment by leninlee** [comment]
Fixed

![screenshot_061915_112744_am](https://cloud.githubusercontent.com/assets/5433592/8247942/3c91ddd6-1676-11e5-8cb9-c73eac00f226.jpg)
