### ISSUE TITLE
At the end of every page there are 2 missing products

### ISSUE THREAD

**Issue by ortokore** [Clan-Creativo/openbox#48]
The whole row should be filled with products.

![screen shot 2015-06-16 at 2 05 07 pm](https://cloud.githubusercontent.com/assets/3596525/8212771/04c6d484-14f4-11e5-8d23-652c6446e9e9.png)

**Comment by leninlee** [comment]
Fixed

![screenshot_061915_112256_am](https://cloud.githubusercontent.com/assets/5433592/8247896/9409d362-1675-11e5-8814-5fb38696a63d.jpg)
