### ISSUE TITLE
Marcas in Footer

### ISSUE THREAD

**Issue by ortokore** [Clan-Creativo/openbox#49]
What are we going to do about this? is it possible to show this like you're showing the marcas in the sidebar? perhaps when scroll-wheel'd over it works? 

![screenshot 2015-06-17 13 49 06](https://cloud.githubusercontent.com/assets/3596525/8213359/b6d89fc4-14f7-11e5-91b2-fd5f076ae5fe.png)

**Comment by leninlee** [comment]
Fixed
![screenshot_061915_111648_am](https://cloud.githubusercontent.com/assets/5433592/8247844/b41f10e6-1674-11e5-921c-41e48a463e85.jpg)

**Comment by ortokore** [comment]
Cool but do you think we could style that scrollbar so it blends with the background? black on black on black black

**Comment by leninlee** [comment]
Fixed
![screenshot_062515_123854_am](https://cloud.githubusercontent.com/assets/5433592/8339072/96d8862c-1ad2-11e5-95a3-2202699ce95b.jpg)
