### ISSUE TITLE
Riding style filtering

### ISSUE THREAD

**Issue by ortokore** [Clan-Creativo/openbox#5]
We need to create these categories ASAP so the client can start attaching the products to the corresponding categories, so we can filter content based on this.

![screenshot 2015-06-10 10 06 42](https://cloud.githubusercontent.com/assets/3596525/8083070/6842e4ea-0f58-11e5-9697-a720e7bfd4cc.png)

**Comment by leninlee** [comment]
Fixed

**Comment by leninlee** [comment]
![screenshot_061215_063614_pm](https://cloud.githubusercontent.com/assets/5433592/8130657/fb54cd18-1131-11e5-89c6-5e27c87f91c0.jpg)

**Comment by ortokore** [comment]
ok REMEMBER -- the STYLES FOR FILTERING are different from the Styles pentagon we're using on the products. For example, for longboards there are 7 items instead of the pentagon's 5; and so forth. According to your screenshot the cats are the same, please correct me if I'm wrong.
