### ISSUE TITLE
Share icons need  url's

### ISSUE THREAD

**Issue by ortokore** [Clan-Creativo/openbox#50]
The share icons for the products aren't working

![screenshot 2015-06-23 01 09 00](https://cloud.githubusercontent.com/assets/3596525/8298813/7e6cfd96-1944-11e5-9df3-81ab2731521c.png)

**Comment by leninlee** [comment]
Fixed

**Comment by ortokore** [comment]
we need for these links to open in a pop up, not _self

**Comment by leninlee** [comment]
Fixed
