### ISSUE TITLE
Came across this in Longboards > Ruedas - Sidebar is wrong

### ISSUE THREAD

**Issue by ortokore** [Clan-Creativo/openbox#51]
![screenshot 2015-06-23 02 14 28](https://cloud.githubusercontent.com/assets/3596525/8299357/95e243a6-194d-11e5-957c-1d1a62ab2867.png)

**Comment by leninlee** [comment]
Fixed
![screenshot_062415_084302_pm](https://cloud.githubusercontent.com/assets/5433592/8333842/58973568-1ab2-11e5-87be-1ce56edc3174.jpg)
