### ISSUE TITLE
Under Patines > Accesorios the sidebar is wrong

### ISSUE THREAD

**Issue by ortokore** [Clan-Creativo/openbox#52]
![screenshot 2015-06-23 02 15 53](https://cloud.githubusercontent.com/assets/3596525/8299364/c9b20de2-194d-11e5-983f-99af613f1b88.png)

**Comment by leninlee** [comment]
Fixed
![screenshot_062415_084302_pm](https://cloud.githubusercontent.com/assets/5433592/8333755/0e1ece42-1ab2-11e5-8843-7342bf4f21f0.jpg)
