### ISSUE TITLE
Longboard > Accesorios sidebar is wrong

### ISSUE THREAD

**Issue by ortokore** [Clan-Creativo/openbox#53]
![screenshot 2015-06-23 02 17 58](https://cloud.githubusercontent.com/assets/3596525/8299385/10a51014-194e-11e5-8d2b-7cebf5ca3b15.png)

**Comment by leninlee** [comment]
Fixed
![screenshot_062415_084302_pm](https://cloud.githubusercontent.com/assets/5433592/8333673/b976d164-1ab1-11e5-81a0-564779f74892.jpg)
