### ISSUE TITLE
Now we can style this part in the checkout process

### ISSUE THREAD

**Issue by ortokore** [Clan-Creativo/openbox#54]
![screenshot 2015-06-23 12 11 36](https://cloud.githubusercontent.com/assets/3596525/8309432/0380d1a4-19a1-11e5-92e1-56e271e816db.png)

**Comment by leninlee** [comment]
Fixed

![screenshot_062415_090051_pm](https://cloud.githubusercontent.com/assets/5433592/8334189/2d261faa-1ab4-11e5-9bf9-dd5b918be2ed.jpg)
