### ISSUE TITLE
Remember this issue with the image proportions

### ISSUE THREAD

**Issue by ortokore** [Clan-Creativo/openbox#56]
IMPORTANT

![screenshot 2015-06-24 12 05 47](https://cloud.githubusercontent.com/assets/3596525/8333460/590846e8-1a69-11e5-83ff-5f3d15f15186.png)

**Comment by leninlee** [comment]
Fixed

**Comment by ortokore** [comment]
they have to be centered vertically

![screenshot 2015-06-24 16 16 17](https://cloud.githubusercontent.com/assets/3596525/8339218/549ce442-1a8c-11e5-88f6-bf247bca5c60.png)

**Comment by leninlee** [comment]
Fixed!.

![screenshot_063015_112942_pm](https://cloud.githubusercontent.com/assets/5433592/8437933/0097f5fa-1f80-11e5-8f46-e43e9567a745.jpg)
