### ISSUE TITLE
Weight shouldn't show up in these specs

### ISSUE THREAD

**Issue by ortokore** [Clan-Creativo/openbox#58]
![screenshot 2015-06-24 16 29 46](https://cloud.githubusercontent.com/assets/3596525/8339488/3542c0ce-1a8e-11e5-9679-92dbb4ab12d6.png)

**Comment by leninlee** [comment]
this list shows, how the attributes order added in backend. so, don't add weight in first while adding.

**Comment by ortokore** [comment]
The weight was actually added last.

**Comment by leninlee** [comment]
Finally Fixed!
![screenshot_063015_111248_pm](https://cloud.githubusercontent.com/assets/5433592/8437587/9000c440-1f7d-11e5-8147-e114aaba3298.jpg)

**Comment by leninlee** [comment]
https://www.openboxstore.cl/tienda/longboard/loaded-cantellated-tesseract-deck-2/
