### ISSUE TITLE
Where do I set up these banners? (for all categories as well)

### ISSUE THREAD

**Issue by ortokore** [Clan-Creativo/openbox#6]
![screenshot 2015-06-10 10 07 55](https://cloud.githubusercontent.com/assets/3596525/8083094/84a8ff70-0f58-11e5-834e-417b3dee829b.png)

**Comment by leninlee** [comment]
We can add here.
http://gs-openboxstore.cl.s207584.gridserver.com/wp-admin/post.php?post=1023&action=edit
