### ISSUE TITLE
Product TOTAL isn't updating with the real total

### ISSUE THREAD

**Issue by ortokore** [Clan-Creativo/openbox#62]
![screenshot 2015-06-24 16 33 34](https://cloud.githubusercontent.com/assets/3596525/8339578/c924a41a-1a8e-11e5-94b8-126159357f1b.png)

**Comment by leninlee** [comment]
Product Url pls

**Comment by ortokore** [comment]
via Skype, Lenin

**Comment by leninlee** [comment]
Base Regular Price + composite Selected product Price  = Total
