### ISSUE TITLE
COMPRAR button has a wrong style

### ISSUE THREAD

**Issue by ortokore** [Clan-Creativo/openbox#63]
The COMPRAR button beneath the composite product dropdown has the wrong style

![screenshot 2015-06-24 16 40 46](https://cloud.githubusercontent.com/assets/3596525/8339705/d12a3f02-1a8f-11e5-94a3-ac9cdd46b166.png)

**Comment by leninlee** [comment]
Fixed 

![screenshot_062615_045123_pm](https://cloud.githubusercontent.com/assets/5433592/8376319/9904c72e-1c23-11e5-8e25-48dc5af6b7ac.jpg)
