### ISSUE TITLE
DELETE SHOP FROM BREADCRUMBS

### ISSUE THREAD

**Issue by ortokore** [Clan-Creativo/openbox#64]
![screenshot 2015-06-24 16 45 46](https://cloud.githubusercontent.com/assets/3596525/8339777/6f483158-1a90-11e5-8240-a47393a09ed1.png)

**Comment by leninlee** [comment]
Fixed

![screenshot_062615_040859_pm](https://cloud.githubusercontent.com/assets/5433592/8375744/baf35b44-1c1d-11e5-9d75-e3dfb97bdf82.jpg)
