### ISSUE TITLE
Arrows for quantity should be like the ones in the dropdowns

### ISSUE THREAD

**Issue by ortokore** [Clan-Creativo/openbox#65]
these arrows
![screenshot 2015-06-24 16 47 19](https://cloud.githubusercontent.com/assets/3596525/8339818/b2720e04-1a90-11e5-86ed-a72945dfe019.png)

should be like these ones
![screenshot 2015-06-24 16 47 14](https://cloud.githubusercontent.com/assets/3596525/8339824/c031d556-1a90-11e5-92ac-78485385267f.png)

**Comment by leninlee** [comment]
Fixed

![screenshot_062615_035546_pm](https://cloud.githubusercontent.com/assets/5433592/8375549/d6c8691a-1c1b-11e5-8b41-774c368fb4be.jpg)
