### ISSUE TITLE
adjustment of the the style of the search bar 

### ISSUE THREAD

**Issue by alvarocova** [Clan-Creativo/openbox#66]
is this possible? ![screen-shot-2015-06-24-at-4 52 53-pm](https://cloud.githubusercontent.com/assets/13010249/8340201/551aa948-1a93-11e5-9bf5-c86be1dd2576.jpg)

**Comment by leninlee** [comment]
Yes possible, Looks Nice. I will fix

**Comment by leninlee** [comment]
Fixed

![screenshot_062615_020732_pm](https://cloud.githubusercontent.com/assets/5433592/8373696/b68b723c-1c0c-11e5-9d04-8f558bd1e3b7.jpg)
