### ISSUE TITLE
Could all image containers be the same size?

### ISSUE THREAD

**Issue by ortokore** [Clan-Creativo/openbox#69]
Now that we've solved the image proportion issue, our container boxes for the product images are different sizes.... could we:

a.  Have all boxes the same size
b. Have the images that are being smaller in height, centered vertical

![screenshot 2015-06-29 09 22 26](https://cloud.githubusercontent.com/assets/3596525/8407766/7115bd9e-1e40-11e5-9353-6eeb9275d6bf.png)

**Comment by leninlee** [comment]
Fixed
![screenshot_063015_091219_pm](https://cloud.githubusercontent.com/assets/5433592/8435035/b8678830-1f6c-11e5-90be-ef31f3b4295d.jpg)
