### ISSUE TITLE
Please make 100% sure that the megamenu is just like in the PSD design

### ISSUE THREAD

**Issue by ortokore** [Clan-Creativo/openbox#8]
I'm not so sure if the font sizes and weight is correct.

![screenshot 2015-06-10 10 10 44](https://cloud.githubusercontent.com/assets/3596525/8083153/ece9fa44-0f58-11e5-9ffa-9d36db383508.png)
![screenshot 2015-06-10 10 10 39](https://cloud.githubusercontent.com/assets/3596525/8083154/ed0874ba-0f58-11e5-850e-0b90b27d484f.png)

**Comment by leninlee** [comment]
Fixed.

![screenshot_061215_035531_pm](https://cloud.githubusercontent.com/assets/5433592/8128338/8b54d3de-111b-11e5-9961-3305fdc2c8fe.jpg)
![screenshot_061215_035459_pm](https://cloud.githubusercontent.com/assets/5433592/8128339/8b64995e-111b-11e5-93d1-d6ed7053372f.jpg)
