### ISSUE TITLE
In Contacto the map should display the correct address

### ISSUE THREAD

**Issue by ortokore** [Clan-Creativo/openbox#9]
the map is showing the area close to the store but not the store itself. The address of the store is:
General Francisco Barceló 36, Las Condes

Also, I believe we should have a PIN with the Store Logo dropping in the correct address (besides having the map center on the address)

pd: where can I edit where the pin should drop?

![screenshot 2015-06-10 10 11 37](https://cloud.githubusercontent.com/assets/3596525/8083204/4e365ffe-0f59-11e5-9cf6-e6ee7db96137.png)

**Comment by leninlee** [comment]
Fixed
